USE project_db;
SHOW TABLES;
SELECT * FROM customer_data;

SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM customer_data
GROUP BY gender;

DESCRIBE customer_data;
/*Q1. What is the total revenue generated by male vs. female customers?
*/
SELECT gender,
SUM(`purchase_amount_(usd)`) AS revenue
FROM customer_data
GROUP BY gender;
/*Q2. Customers used discount but spent more than average
*/
SELECT customer_id, `purchase_amount_(usd)`
FROM customer_data
WHERE discount_applied = 'Yes'
AND `purchase_amount_(usd)` >
(
    SELECT AVG(`purchase_amount_(usd)`)
    FROM customer_data
);
/*Q3. Top 5 products with highest average purchase
*/
SELECT item_purchased,
ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
#Q4. Compare the average purchase amount between Standard and Express Shipping
SELECT shipping_type,
AVG(`purchase_amount_(usd)`) AS avg_purchase_amount
FROM customer_data
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue
# between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(*) AS total_customers,
AVG(`purchase_amount_(usd)`) AS avg_spend,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer_data
GROUP BY subscription_status;
#Q6. Which 5 products have the highest percentage of 
#purchases with discounts applied?
SELECT item_purchased,
ROUND(
AVG(discount_applied = 'Yes') * 100,
2
) AS discount_percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
#Q7. Segment customers into New, Returning, and Loyal based on total number 
#of previous purchases, and show the count of each segment
SELECT customer_segment,
COUNT(*) AS total_customers
FROM
(
    SELECT
    CASE
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer_data
) AS customer_type
GROUP BY customer_segment;
#Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS
(
    SELECT
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank,
        category,
        item_purchased,
        COUNT(*) AS total_orders
    FROM customer_data
    GROUP BY category, item_purchased
)

SELECT item_rank,
category,
item_purchased,
total_orders
FROM item_counts
WHERE item_rank <= 3;
#Q9. Are customers who are repeat buyers
# (more than 5 previous purchases) also likely to subscribe?
SELECT
subscription_status,
COUNT(*) AS "Number of Customers"
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY subscription_status;
#Q10. What is the revenue contribution of each age group?
SELECT age_group,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM
(
    SELECT
    CASE
        WHEN age BETWEEN 18 AND 25 THEN 'Young Adult'
        WHEN age BETWEEN 26 AND 35 THEN 'Adult'
        WHEN age BETWEEN 36 AND 50 THEN 'Middle-aged'
        ELSE 'Senior'
    END AS age_group,
    `purchase_amount_(usd)`
    FROM customer_data
) AS t
GROUP BY age_group
ORDER BY total_revenue DESC;


SHOW DATABASES: